# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./CloudSynkr.App
      
    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./CloudSynkr.App

    - name: Test
      run: dotnet test
      #--verbosity normal
#.Synkr/CloudSynkr.App/CloudSynkr.App.csproj
    - name: Publish
      run: dotnet publish -c release --output ./publish --no-restore --no-build /p:DebugType=None /p:DebugSymbols=false -r win-x64 --self-contained -p:PublishReadyToRun=true -p:PublishSingleFile=true
      working-directory: .Synkr/CloudSynkr.App

    
    
    
    
