on:
    workflow_call:
  
jobs:
    publish:
        name: Publish ${{ matrix.os }}
        runs-on: ubuntu-latest
    
        strategy:
          matrix:
            os: [win-x64,osx-x64,linux-x64]
    
        steps:
        - uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x
        
        - name: Publish ${{ matrix.os }}
          run: dotnet publish -c release --output ./publish-${{ matrix.os }} /p:DebugType=None /p:DebugSymbols=false -r ${{ matrix.os }} --self-contained -p:PublishReadyToRun=true -p:PublishSingleFile=true ./CloudSynkr.App.csproj
          working-directory: ./CloudSynkr.App
    
        - name: List published content
          run: ls -l ./publish-${{ matrix.os }}
          working-directory: ./CloudSynkr.App
        
        - name: Upload release artifact for ${{ matrix.os }}
          uses: actions/upload-artifact@v4
          with:
              name: Synkr-${{ matrix.os }}
              path: ./CloudSynkr.App/publish-${{ matrix.os }}/
              if-no-files-found: error