  on:
    workflow_call:
  
  jobs:
      tagging:
        runs-on: ubuntu-latest
        outputs:
          new_tag: ${{ steps.tag.outputs.new_tag  }}
        permissions:
          contents: write
        
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: '0'
          
          - name: Bump version and push tag
            id: tag
            uses: anothrNick/github-tag-action@1.67.0
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              WITH_V: true 