on:
    workflow_call:
  
jobs:
    reusable_workflow_job:
        runs-on: ubuntu-latest
  
        steps:
            - uses: actions/checkout@v4
            - name: Test
              run: dotnet test --verbosity normal